name: Flask CI

on: [push, pull_request]  # Runs on push or PR

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repo

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10  # Use Python 3.10

      - name: Install Dependencies
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate
          pip install -r requirements.txt  # Install dependencies

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/  # Run tests (assuming test files exist)

      - name: Lint Code
        run: |
          source venv/bin/activate
          flake8 app.py  # Check for PEP8 compliance
